const sweetsDatabase =[
         {
            name: "🍯Медовый торт / Классик",
            type: "cake",
            price: 85,
            shop: "Sweet House Dushanbe",
            address:"Ул. Бухоро, 43 (ориентир:Гимназия №1)",
            shopUrl: "https:/.sweetsDushanbe.com",
            description: "Нежный медовый торт с орехами",
            image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400",
        },
        {
            name: "🍭Ассорти шоколадных конфет",
            type: "chocolate",
            price: 45,
            shop: "Chocolate Boutique",
            address: "ТЦ 'Ашан', 1-ый этаж",
            shopUrl: "https://chocolatetj.com",
            description: "Бельгийский шоколад ручной работы",
            image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=400",
        },
        {
            name: "🧇Пахлава с фисташками",
            type: "baklava",
            price: 35,
            shop: "Oriental Sweets",
            address: "Рынок 'Мехргон', центральный ряд",
            shopUrl: "https://orientalsweets.tj",
            description: "Домашняя пахлава по турецкому рецепту",
            image: "https://images.unsplash.com/photo-1581683783653-a22f9b78bdd5?w=400",
        },
        {
            name: "😋Тирамису классический",
            type: "cake",
            price: 120,
            shop: "Caffé Dolce",
            shopUrl: "https://caffedolce.tj",
            description: "Итальянский десерт с маскарпоне",
            image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400",
        },
        {
            name: "🍧Пломбир вафельный стаканчик",
            type: "icecream",
            price: 15,
            shop: "Ice Cream Paradise",
            shopUrl: "https://icecream.tj",
            description: "Классическое мороженое из натуральных сливок.",
            image: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=400",
        },
        {

            name: "🥯Макарунс ассорти",
            type: "macaron",
            price: 65,
            shop: "French Bakery",
            shopUrl: "https://frenchbakery.tj",
            description: "6 штук разных вкусов",
            image: "https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=400",
        },
        { 
            name:"🥮Турецкая пахлава",
            type:"baklava",
            price:120,
            shop:"Baklava House Dushanbe",
            shopUrl:"https://instagram.com/baklava_tj",
            description:"Настоящая турецкая пахлава с отборными фисташками и натуральным медом. Тает во рту!",
            image:"https://images.unsplash.com/photo-1519676867240-f03562e64548?q=80&w=1000&auto=format&fit=crop",
        
        },
        {
            name: "🧁бенто Торты",
            type: "cake",
            price: 140,
            shop: "Арка",
            shopUrl: "https://www.instagram.com/arka_tj",
            description: "бенто торты с выбраной надписью или  фотографией",
            image: "https://menu.tj/storage/logo/1638274351.png",
        },
        {
            name: "🍫Дубайский шоколад (handmade)",
            type: "chocolate",
            price: 120,
            shop: "Chocolate Botutique Dushanbe",
            shopUrl: "https://instagram.com/local_shop",
            description:"Тот самый вирусный шоколад с начинкой из хрустящего теста катаифии натуральной фисташковой пасты. Хит продаж 2025-2026! ",
            image: "https://menu.tj/storage/logo/dubai_choco.png",
        },
        {
            name: "🍪моти ассорти",
            type: "desert",
            price: 15,
            shop: "Yummy Mochi Tj",
            shopurl: "https//instagram.com/mochi_mix.png",
            description: "Нежное японское лакомство из рисового теста с разнообразными кремовыми начинками",
            image: "https://menu.tj/storage/logo/mochi_mix.png"
        },
        {
            name: "🤤Парварда",
            type: "desert",
            price: 25,
            shop: "мехргон базар",
            shopUrl: "https://example.tj/shop",
            description: "Натуральная восточная сладость в виде белых подушечекв муке",
            image: "https://example.tj/images/parvarda.jpg",
        },
        {
            name: "🍨Классический Пломбир",
            type: "icecream",
            price: 10,
            shop: "Мороженное Ватан",
            address:"проспект Рудаки, 20 (ориентир: ЦУМ)",//новое поле
            shopurl: "https://www.instagram.com/vatan_tj/",
            description: "тот самый вкус из детстваЖнасыщенный сливочный вкуси нежная структура. ",
            image: "https://images.unsplash.com/photo-1567206563064-6f60f40a2b57?w=400",
        },
        {
            name: "🧊Жареннное мороженое (роллы)",
            type: "icecream",
            price: 30,
            shop: "Thai rolls Dushanbe",
            address: "ТЦ 'СИЕМА МОЛЛ', 3-ий этаж",//указываем конкретное место
            shopUrl: "https://instsgram.com/thai_rolls_tj",
            description: "Тайское мороженое,которое готовят прямо при тебе на ледяной плите.",
            image: "https://images.unsplash.com/photo-1562911674-d4999cc7633f?=w400",
        },
        {
            name: "🏡Наполеон домашний",
            type: "pastry",
            price: 95,
            shop: "Домашняя выпечка",
            shopUrl: "https://homebaking.tj",
            description: "Классический торт Наполеон",
            image: "https://images.unsplash.com/photo-1551029504-0808cc1f8d9c?w=400",
        },
        {
            name: "🍿Чизкейк Сан-Себастьян",
            type: "cake",
            price: 35,
            shop: "Coffee & Cake",
            shopurl: "https://instagram.com/coffeecake_tj",
            description: "Знаменитый 'жженый' чизкейк с нежной кремовой текстурой внутри и карамельной корочкой снаружи.",
            image: "https://menu.tj/storage/logo/san_sebastian.png",
        }, 
        {
            name: "🍯Чак-чак медовый",
            type: "baklava",
            price: 25,
            shop: "Татарские сладости",
            shopUrl: "https://tatarfood.tj",
            description: "Традиционные медовые шарики",
            image: "https://images.unsplash.com/photo-1581683783653-a22f9b78bdd5?w=400",
        },
        {
            name: "🍓Клубничный чизкейк",
            type: "cake",
            price: 110,
            shop: "Cheesecake Factory",
            shopUrl: "https://cheesecake.tj",
            description: "Нежный чизкейк со свежей клубникой",
            image: "https://images.unsplash.com/photo-1524351199678-882a83a2bcb1?w=400",
        },
        ];